# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"



# System update, upgrades, package search, etc.
alias search='apt search'
alias checkupd='sudo apt update'
alias upd='sudo apt update && sudo apt upgrade'
alias inst='sudo apt install'
alias reinst='sudo apt install --reinstall'
alias rem='sudo apt remove --purge --autoremove'


# Programming specific
alias mysql='/usr/bin/mysql'
alias mariadb='/usr/bin/mariadb'
alias java21='sudo update-alternatives --set java /usr/lib/jvm/java-21-openjdk-21.0.3.0.9-1.fc40.x86_64/bin/java'
alias java17='sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-17.0.10.0.7-3.fc40.x86_64/bin/java'
alias mongofix='cd /var/lib/mongodb && sudo chown -R krit:krit /var/lib/mongodb && sudo chown krit:krit /tmp/mongodb-27017.sock || cd /var/lib/mongodb && sudo rm -r mongod.lock'


# General setup
alias zshrc='source ~/.zshrc'
alias zshenv='source ~/.zshenv'
alias sudo='sudo '
alias c='clear'
alias reb='reboot'
alias del='sudo rm -rf'


# System navigation setup
alias .1='cd ..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
alias .6='cd ../../../../../..'
alias ls='eza -al --color=always --group-directories-first'
alias ll='ls -l'
alias la='ls -A'
alias del='sudo rm -r'
alias cp='cp -i'
alias mkdir='mkdir -p'
alias h='history'
alias which='type -a'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias erep='egrep --color=auto'
alias untar='tar -xvzf'


# System navigation
alias downloads='cd ~/Downloads'
alias lib='cd /usr/lib'
alias config='cd ~/.config/'


# Version control
alias clone='git clone'
alias clonedepth1='git clone --depth=1'
alias gac='git add -A && git commit -m "directory management" && git push'
alias gitkeep='find . -type d -empty -not -path "./.git/*" -exec touch {}/.gitkeep \;'
alias gpamaster='cd /home/krit/0001_Github_Repos && ./gitpullmaster.sh'
alias gpamain='cd /home/krit/0001_Github_Repos && ./gitpullmain.sh'


# USI SSH and repositories navigation
alias at='ssh nicolk@atelier.inf.usi.ch'
alias usiinf='cd /home/krit/0001_Github_Repos/0001_USI/0001_Usi_Inf'
alias usiinfgeneral='cd /home/krit/0001_Github_Repos/0001_USI/0001_Usi_Inf/0001_General/USIinfGeneral'
alias usiinfss='cd /home/krit/0001_Github_Repos/0001_USI/0002_Semester_Specific'
alias usiinfos='cd /home/krit/0001_Github_Repos/0001_USI/0003_Other_Students'

#alias usiinf12='cd /home/krit/0001_Github_Repos/0001_USI/0001_Usi_Inf/0002_Bachelor/USIinfBS12/'
#alias usiinf34='cd /home/krit/0001_Github_Repos/0001_USI/0001_Usi_Inf/0002_Bachelor/USIinfBS34/'
#alias usiinf56='cd /home/krit/0001_Github_Repos/0001_USI/0001_Usi_Inf/0002_Bachelor/USIinfBS34/'
#alias usiinfma12='cd /home/krit/0001_Github_Repos/0001_USI/0001_Usi_Inf/0003_Master/USIinfMA12/'
#alias usiinfma34='cd /home/krit/0001_Github_Repos/0001_USI/0001_Usi_Inf/0003_Master/USIinfMA34/'


# Personal repos navigation
alias setup='cd /home/krit/0001_Github_Repos/0002_Linux_Setup'
alias personal='cd /home/krit/0001_Github_Repos/0003_Personal_Repos'


# Fun commands (not in use for usi-focused system)
#alias boxesdog='echo "Popi Popi" | boxes -d dog -a c'
#alias cv='cava'
#alias infbonsai='cbonsai -S'
#alias pokdialga='pokemon-colorscripts --name dialga'

# Gitlab token for SA4
export GITLAB_ACCESS_TOKEN=glpat-5Az2eKcVDyp3QND11Btv
